version: '3.1'
services:
  app:
    container_name: pismo-application
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - pismo-database
  pismo-database:
    image: postgres:latest
    ports:
      - "5432:15432"
    environment:
      - POSTGRES_PASSWORD=p@s5w0rd!
      - POSTGRES_USER=postgres
      - POSTGRES_DB=pismo